### ISSUE TITLE
Migration to Open Collective

### ISSUE THREAD

**Issue by RangerMauve** [datproject/organization#16]
This issue is the main tracker of tasks that we need to finish in order to migrate the Dat Foundation from CS&S to the Open Collective by the Dat Migration Working Group.

If you're interested in helping out with any of these tasks feel free to post here so we can track it. If you think more stuff should be added, ping @zootella @Frando and @RangerMauve to get it figured out.

One of the goals of this working group is to do as much coordination in the open as possible so we'll keep as many updates as we can in this GH issue. That said we also have a Discord group chat for coordinating stuff in real time. Feel free to post here if you'd like to be added there.

## TODO / Figure out

- [ ] Figure out board membership / how many people / who wants in
- [ ] Check that we can keep logos of grant givers from past on the website.
- [x] Can we add EU logos from NLNet to website? Yes, we can, should do it.
- [ ] Check with projects to see if we can get their logos too
- [ ] Figure out which resources should be migrated (cloudflare / netlify / mailchimp / etc.). How will they be paid for?
- [ ] Consider board members having access to resources and process for adding / removing them- Consider primary account? Like shared email address
- [ ] Consider if bank account could be made with fiscal sponsor / or make one
- [ ] Reach out to CS&S to get initial talks going @RangerMauve @zootella 
- [ ] Reach out to Open Source Collective to talk to them. @RangerMauve @zootella 
- [x] Reach out to SSB to talk about Open Source Collective @RangerMauve 
- [ ] Update logo to reflect that there's a Dat but not a `dat://`
- [ ] Decide if we keep the Dat Foundation name for new entity (+1s from WG so far)

**Comment by okdistribute** [comment]
Yes we can ad logos from NLNet to website, github.com/dat-foundation-website -- should be as easy as adding a markdown file.

**Comment by okdistribute** [comment]
@RangerMauve we won't need to make a bank account if we use open collective, as people will invoice open collective directly. so we can strike that one from the list

**Comment by RangerMauve** [comment]
@okdistribute Ah, that point was brought up because we were wondering if it'd sometimes make sense to have payments processed directly by the fiscal sponsor in order to skip the extra fees taken by OpenCollective. Check out the meeting notes for details: https://hackmd.io/D9Lk65auTIe32RHVI8FUVg

**Comment by okdistribute** [comment]
@RangerMauve sure that makes sense, but the bank account will also have some fees attached as well, and if people are subcontracting to it, will have some accounting wizardry to figure out. But perhaps that $$ is less than 5%, indeed!

**Comment by RangerMauve** [comment]
Current focus is to send out an email to CS&S by Friday night (July 17 2020)  about what we've been talking about regarding Open Collective and then to reach out to the Open Source Collective and figure stuff out from there. 😁

**Comment by RangerMauve** [comment]
Got some feedback from SSB folks on Open Source Collective. %9isw/4MtbyRGqtneMcGYNTpale+mJ3RW8mrc0awPNz8=.sha256

Andre seems to like it. "Open Source Collective is really nice and well run, rarely is late on payouts, etc. The best run host in my experience. Don’t think twice, I can’t see any better option for Dat"

**Comment by dkastl** [comment]
Not sure if this is an interesting alternative, but a few months ago I applied for https://funding.communitybridge.org/ with an Open Source project and got it accepted. The Linux Foundation does not charge transaction fees.

**Comment by RangerMauve** [comment]
CS&S got back to us, need to reach out to Open Source Collective and start talking about the migration. This week will be hard for that because I'm super busy, unless someone else can get started on it, I'll set a reminder to write up a draft and get it reviewed by the WG on Monday.

**Comment by RangerMauve** [comment]
Probs gonna get an intro from Danielle first.

**Comment by RangerMauve** [comment]
Sent out email to Pia, person that Danielle intro'd. They're on break until the 14th

**Comment by RangerMauve** [comment]
Pia from Open Collective got in touch, gonna need to make our balance zero in our current open collective. This'll be done by having Open Source Collective send an invoice to us for all our funds, then once CS&S approves of it, they can switch it all over.

I think after that we'll need some agreement signed with OSC and CS&S saying they'll handle our assets from now on.

**Comment by okdistribute** [comment]
This is great news @RangerMauve !

**Comment by RangerMauve** [comment]
Danielle is currently working with the OC folks to transfer the funds and draft up a contract.

**Comment by RangerMauve** [comment]
Pending ons ending the terms over to OC, last update, Danielle said she was waiting for Joe to come back from vacation, seems she's on vacation now until the 7th. We'll likely get an update after she's back. Soliciting questions for the OC terms in the meantime, will send the questions over tomorrow to get answers.

**Comment by todrobbins** [comment]
I just stopped by the OpenCollective and it's looking great! Nice work everyone!
